//const o let?
let baseDeDatos = {
    Aretes : [
      {
        id: 1,
        nombre: "Aretes de flor",
        precio: 5.99,
        opciones: ["Blanco","Celeste","Rosado","Morado"],
        categorias:["Amistad"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 2,
        nombre: "Aretes de frutas",
        precio: 5.99,
        opciones: ["Sandía","Fresa","Uva","Cereza"],
        categorias:["Amistad"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 3,
        nombre: "Aretes ganchos",
        precio: 4.99,
        opciones: ["Sin opciones por el momento"],
        categorias:["Amistad"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      // Pendiente: agregar objetos para otros diseños de aretes
    ],

    //Brazaletes tejidos
    BrazaletesTejidos: [
      {
        id: 1,
        nombre: "Brazalete Estrella",
        precio: 7.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 2,
        nombre: "Brazalete - dije Guitarra",
        precio: 9.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 3,
        nombre: "Brazalete - dije Mariposa",
        precio: 9.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 4,
        nombre: "Brazalete - dije Corazón",
        precio: 9.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 4,
        nombre: "Brazalete - dije ",
        precio: 9.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      // Pendiente: agregar objetos para otros diseños de brazaletes tejidos
    ],


    BrazaletesBisuteria: [
      {
        id: 1,
        nombre: "Brazalete de bisutería - Softs ",
        precio: 14.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 2,
        nombre: "Brazalete de bisutería - Indie slim ",
        precio: 5.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro","Multicolor"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 3,
        nombre: "Brazalete de bisutería - Indie slim bicolor",
        precio: 5.99,
        opciones: ["Rojo","Rosado","Celeste","Lila",
        "Verde","Amarillo","Negro","Multicolor"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 4,
        nombre: "Brazalete de bisutería - Indie slim frutas",
        precio: 7.99,
        opciones: ["Sandía","Fresa","Uva","Pomelo","Naranja","Limón","Piña"],
        categorias:["Amistad","Parejas"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 5,
        nombre: "Duo Brazalete de bisutería - BFF's",
        precio: 19.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
        "Verde","Amarillo","Negro","Multicolor"],
        categorias:["Amistad","Graduación"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      // Pendiente: agregar objetos para otros diseños de brazaletes de bisutería
    ],

    PortaAnteojos: [
      {
        id: 1,
        nombre: "Porta anteojos de Bisuteria - Soft",
        precio: 14.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
        "Verde","Amarillo","Negro","Multicolor"],
        categorias:["Sin Categoria por el momento"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 2,
        nombre: "Porta anteojos de Bisuteria - Indie",
        precio: 14.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
        "Verde","Amarillo","Negro","Multicolor"],
        categorias:["Sin Categoria por el momento"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 3,
        nombre: "Porta anteojos de Bisuteria - Minimalista",
        precio: 14.99,
        opciones: ["Blanco","Negro","Beige","Gris","Café","Multicolor"],
        categorias:["Sin Categoria por el momento"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      // Pendiente: agregar más objetos para otros diseños de porta anteojos
    ],
    collaresGargantillas: [
      {
        id: 1,
        nombre: "Gargantilla de Bisuteria - Soft",
        precio: 14.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
        "Verde","Amarillo","Negro"],
        categorias:["Sin Categoria por el momento"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      {
        id: 2,
        nombre: "Gargantilla de Bisuteria - Indie",
        precio: 14.99,
        opciones: ["Rojo","Rosado","Celeste","Lila",
        "Verde","Amarillo","Negro","Multicolor"],
        categorias:["Sin Categoria por el momento"],
        talla:["XS","S","M","L","XL"],
        imagen: "",
      },
      // Pendiente: agregar más objetos para otros diseños de collares/gargantillas
    ],
  };
  