//const o let?
  export let Jujudata = [

    //SECCION DE ARETES******************************************************************************
    {
      id: 0,
      nombre: "Aretes de flor",
      precio: 5.99,
      opciones: ["Blanco","Celeste","Rosado","Morado"],
      categorias:"arete",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/a4/26/4d/a4264db0e324b81d624c97ff47e8eb6e.jpg",
      
    },
    {
      id: 1,
      nombre: "Aretes de frutas",
      precio: 5.99,
      opciones: ["Sandía","Fresa","Uva","Cereza"],
      categorias:"arete",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/64/44/60/64446071925caa6ca6e308dabb3aae59.jpg",
    },
    {
      id: 2,
        nombre: "Aretes de ganchos",
        precio: 4.99,
        opciones: ["Sin opciones por el momento"],
        categorias:"arete",
        talla:["XS","S","M","L","XL"],
        imagen: "https://i.pinimg.com/564x/11/82/41/1182418fe9b42b060ab7f08f7afe0401.jpg",
    },

    //SECCIÓN BRAZALETES TEJIDOS **************************************************************
    {
      id: 3,
        nombre: "Brazalete Mariposa",
        precio: 7.99,
        opciones: ["Blanco","Rojo","Rosado","Celeste",
        "Lila","Verde","Amarillo","Negro"],
        categorias:"tejido",
        talla:["XS","S","M","L","XL"],
        imagen: "https://i.pinimg.com/564x/b2/9f/ba/b29fbad58204010e3f0e726791e697e1.jpg",
    },
    {
      id: 4,
      nombre: "Brazalete - dije Infinito",
      precio: 9.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste",
      "Lila","Verde","Amarillo","Negro"],
      categorias:"tejido",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/bf/f7/50/bff75073cbf72d2cf1f1b46de38d0ac3.jpg",
    },
    {
      id: 5,
      nombre: "Brazalete - dije Mariposa",
      precio: 9.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste",
      "Lila","Verde","Amarillo","Negro"],
      categorias:"tejido",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/8f/50/51/8f505179e3252a8762b06e14ad164088.jpg",
    },
    {
      id: 6,
      nombre: "Brazalete - dije Corazón",
      precio: 9.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste",
      "Lila","Verde","Amarillo","Negro"],
      categorias:"tejido",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/bc/ab/c4/bcabc403d178beb2674e280d90ba5f44.jpg",
    },
    {
      id: 7,
      nombre: "Brazalete - dije ",
      precio: 9.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste",
      "Lila","Verde","Amarillo","Negro"],
      categorias:"tejido",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/f6/a8/60/f6a860b34841e9ddf67d5d110d6d3eac.jpg",
    },

    //SECCIÓN BRAZALETES BIZUTERIA ***************************************************************
    {
      id: 8,
      nombre: "Brazalete de bisutería - Softs ",
      precio: 14.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste",
      "Lila","Verde","Amarillo","Negro"],
      categorias:"bizuteria",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/36/3d/c2/363dc2aed180bcbe935c2b621354006e.jpg",
    },
    {
      id: 9,
      nombre: "Brazalete de bisutería - Indie slim ",
      precio: 5.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste",
      "Lila","Verde","Amarillo","Negro","Multicolor"],
      categorias:"bizuteria",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/ff/c7/9e/ffc79e48ba3ee2e783d321b43de3325f.jpg",
    },
    {
      id: 10,
      nombre: "Brazalete de bisutería - Indie slim bicolor",
      precio: 5.99,
      opciones: ["Rojo","Rosado","Celeste","Lila",
      "Verde","Amarillo","Negro","Multicolor"],
      categorias:"bizuteria",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/84/e9/85/84e985059941d817e12c17ab8987ba5d.jpg",
    },
    {
      id: 11,
      nombre: "Brazalete de bisutería - Indie slim flor",
      precio: 7.99,
      opciones: ["Sandía","Fresa","Uva","Pomelo","Naranja","Limón","Piña"],
      categorias:"bizuteria",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/48/c7/ac/48c7ac393f1a4c373bbb6f9a4b2d2683.jpg",
    },
    {
      id: 12,
      nombre: "Duo Brazalete de bisutería - BFF's",
      precio: 19.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
      "Verde","Amarillo","Negro","Multicolor"],
      categorias:"bizuteria",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/e0/52/ad/e052ad1f0771208e2126dc20a3965b73.jpg",
    },

    //SECCIÓN PORTANTEOJOS *************************************************************************
    {
      id: 13,
      nombre: "Porta anteojos de Bisuteria - Soft",
      precio: 14.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
      "Verde","Amarillo","Negro","Multicolor"],
      categorias:"anteojos",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/02/3b/10/023b1009ed87e34a8bd1f19aae08bb0d.jpg",
    },
    {
      id: 14,
      nombre: "Porta anteojos de Bisuteria - Indie",
      precio: 14.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
      "Verde","Amarillo","Negro","Multicolor"],
      categorias:"anteojos",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/a2/89/79/a28979a82f0c574709e546df586cd3ae.jpg",
    },
    {
      id: 15,
      nombre: "Porta anteojos de Bisuteria - Minimalista",
      precio: 14.99,
      opciones: ["Blanco","Negro","Beige","Gris","Café","Multicolor"],
      categorias:"anteojos",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/55/63/59/5563591a43de65f037eea3239edc8eb5.jpg",
    },

    //SECCIÓN GARGANTILLAS **********************************************************************
    {
      id: 16,
      nombre: "Gargantilla / Collar de Bizuteria - Soft",
      precio: 14.99,
      opciones: ["Blanco","Rojo","Rosado","Celeste","Lila",
      "Verde","Amarillo","Negro"],
      categorias:"collares",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/5c/de/12/5cde12e849c3cd909899b1b30cf4ec0b.jpg",
    },
    {
      id: 17,
      nombre: "Gargantilla / Collar de Bizuteria - Indie",
      precio: 14.99,
      opciones: ["Rojo","Rosado","Celeste","Lila",
      "Verde","Amarillo","Negro","Multicolor"],
      categorias:"collares",
      talla:["XS","S","M","L","XL"],
      imagen:"https://i.pinimg.com/564x/ca/2b/98/ca2b987cb6ec0cc4fca1d007d3a31034.jpg"
    },
    //SECCIÓN BAUTIZOS ************************************************************************************
    {
      id: 18,
      nombre: "Rosario bizuteria tradicional",
      precio: 14.99,
      opciones: ["Blanco","Negro"],
      categorias:"collares",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/55/99/5c/55995c351f60584e54545d59cba6af2e.jpg",
    },
    {
      id: 19,
      nombre: "Rosario bizuteria perlas",
      precio: 14.99,
      opciones: ["Blanco","Negro"],
      categorias:"collares",
      talla:["XS","S","M","L","XL"],
      imagen: "https://i.pinimg.com/564x/ad/2e/5a/ad2e5ad1071c2509fc990df149272eee.jpg",
    },
  ]


//<img src="./img/x.png" alt="">